using PAP.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PAP.DataAccess
{
    /// <summary>
    /// 
    /// </summary>
    public class DataAccessLayer
    {
        /// <summary>
        /// 
        /// </summary>
        public DataAccessLayer()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public IEnumerable<Book> GetAllBooks()
        {   /*
            var books2 = new List<Book>
            {
                new Book
                {
                    Id = 1,
                    Name = "The Silent Horizon",
                    Title = "The Silent Horizon",
                    Category = "Fiction",
                    Publisher = "HarperCollins",
                    Author = "Eleanor Brooks",
                    Description = "A mysterious journey across a forgotten landscape reveals secrets buried for generations.",
                    PublicationDate = new DateTime(2021, 3, 15),
                    Height = 8.5,
                    Width = 5.5,
                    Price = 18.99m,
                    IsBestSeller = true,
                    Genre = "Mystery",
                    IsInStock = true,
                    CreatedAt = new DateTime(2021, 3, 20),
                    UpdatedAt = new DateTime(2026, 9, 1)
                },
                new Book
                {
                    Id = 2,
                    Name = "Beyond the Stars",
                    Title = "Beyond the Stars",
                    Category = "Science Fiction",
                    Publisher = "Penguin Random House",
                    Author = "Marcus Reed",
                    Description = "Humanity's first expedition beyond the solar system encounters something unexpected.",
                    PublicationDate = new DateTime(2020, 7, 10),
                    Height = 9.0,
                    Width = 6.0,
                    Price = 22.50m,
                    IsBestSeller = true,
                    Genre = "Science Fiction",
                    IsInStock = true,
                    CreatedAt = new DateTime(2020, 7, 15),
                    UpdatedAt = new DateTime(2026, 8, 25)
                },
                new Book
                {
                    Id = 3,
                    Name = "The Art of C#",
                    Title = "The Art of C#",
                    Category = "Technology",
                    Publisher = "O'Reilly Media",
                    Author = "Daniel Foster",
                    Description = "A practical guide to writing clean, maintainable and modern C# applications.",
                    PublicationDate = new DateTime(2023, 1, 12),
                    Height = 9.2,
                    Width = 7.0,
                    Price = 45.99m,
                    IsBestSeller = true,
                    Genre = "Programming",
                    IsInStock = true,
                    CreatedAt = new DateTime(2023, 1, 20),
                    UpdatedAt = new DateTime(2026, 9, 5)
                },
                new Book
                {
                    Id = 4,
                    Name = "Echoes of Winter",
                    Title = "Echoes of Winter",
                    Category = "Fiction",
                    Publisher = "Simon & Schuster",
                    Author = "Clara Mitchell",
                    Description = "A family returns to their ancestral home and discovers an unfinished story.",
                    PublicationDate = new DateTime(2019, 11, 4),
                    Height = 8.4,
                    Width = 5.4,
                    Price = 16.75m,
                    IsBestSeller = false,
                    Genre = "Drama",
                    IsInStock = true,
                    CreatedAt = new DateTime(2019, 11, 10),
                    UpdatedAt = new DateTime(2026, 7, 12)
                },
                new Book
                {
                    Id = 5,
                    Name = "The Last Algorithm",
                    Title = "The Last Algorithm",
                    Category = "Technology",
                    Publisher = "MIT Press",
                    Author = "Nathan Cole",
                    Description = "A software engineer discovers an algorithm capable of predicting human decisions.",
                    PublicationDate = new DateTime(2022, 5, 18),
                    Height = 9.1,
                    Width = 6.7,
                    Price = 34.99m,
                    IsBestSeller = true,
                    Genre = "Tech Thriller",
                    IsInStock = true,
                    CreatedAt = new DateTime(2022, 5, 25),
                    UpdatedAt = new DateTime(2026, 8, 30)
                },
                new Book
                {
                    Id = 6,
                    Name = "Gardens of the Moon",
                    Title = "Gardens of the Moon",
                    Category = "Fantasy",
                    Publisher = "Tor Books",
                    Author = "Isabelle Grant",
                    Description = "A young traveler discovers a hidden kingdom existing between dreams and reality.",
                    PublicationDate = new DateTime(2018, 6, 21),
                    Height = 8.8,
                    Width = 5.8,
                    Price = 19.95m,
                    IsBestSeller = true,
                    Genre = "Fantasy",
                    IsInStock = true,
                    CreatedAt = new DateTime(2018, 6, 30),
                    UpdatedAt = new DateTime(2026, 6, 18)
                },
                new Book
                {
                    Id = 7,
                    Name = "Modern Cybersecurity",
                    Title = "Modern Cybersecurity",
                    Category = "Technology",
                    Publisher = "Wiley",
                    Author = "Robert Hayes",
                    Description = "An introduction to modern security architecture, threat modeling and incident response.",
                    PublicationDate = new DateTime(2024, 2, 14),
                    Height = 10.0,
                    Width = 7.2,
                    Price = 49.99m,
                    IsBestSeller = false,
                    Genre = "Cybersecurity",
                    IsInStock = true,
                    CreatedAt = new DateTime(2024, 2, 20),
                    UpdatedAt = new DateTime(2026, 9, 10)
                },
                new Book
                {
                    Id = 8,
                    Name = "A River Between Us",
                    Title = "A River Between Us",
                    Category = "Romance",
                    Publisher = "Harlequin",
                    Author = "Sophia Bennett",
                    Description = "Two childhood friends meet again years later on opposite sides of a difficult decision.",
                    PublicationDate = new DateTime(2021, 8, 2),
                    Height = 8.3,
                    Width = 5.3,
                    Price = 14.99m,
                    IsBestSeller = true,
                    Genre = "Romance",
                    IsInStock = true,
                    CreatedAt = new DateTime(2021, 8, 10),
                    UpdatedAt = new DateTime(2026, 8, 1)
                },
                new Book
                {
                    Id = 9,
                    Name = "The Forgotten Empire",
                    Title = "The Forgotten Empire",
                    Category = "History",
                    Publisher = "Oxford University Press",
                    Author = "Henry Wallace",
                    Description = "An exploration of a powerful ancient civilization and the reasons behind its disappearance.",
                    PublicationDate = new DateTime(2017, 4, 11),
                    Height = 9.5,
                    Width = 6.5,
                    Price = 32.00m,
                    IsBestSeller = false,
                    Genre = "History",
                    IsInStock = true,
                    CreatedAt = new DateTime(2017, 4, 20),
                    UpdatedAt = new DateTime(2026, 5, 14)
                },
                new Book
                {
                    Id = 10,
                    Name = "Learning Python",
                    Title = "Learning Python",
                    Category = "Technology",
                    Publisher = "O'Reilly Media",
                    Author = "James Carter",
                    Description = "A hands-on introduction to Python programming, automation and data processing.",
                    PublicationDate = new DateTime(2023, 9, 5),
                    Height = 9.3,
                    Width = 7.0,
                    Price = 42.99m,
                    IsBestSeller = true,
                    Genre = "Programming",
                    IsInStock = true,
                    CreatedAt = new DateTime(2023, 9, 12),
                    UpdatedAt = new DateTime(2026, 9, 2)
                },
                new Book
                {
                    Id = 11,
                    Name = "The Ocean Between Worlds",
                    Title = "The Ocean Between Worlds",
                    Category = "Science Fiction",
                    Publisher = "Orbit",
                    Author = "Laura Anderson",
                    Description = "Scientists discover a parallel ocean beneath Earth's surface.",
                    PublicationDate = new DateTime(2022, 10, 8),
                    Height = 8.7,
                    Width = 5.7,
                    Price = 21.99m,
                    IsBestSeller = false,
                    Genre = "Science Fiction",
                    IsInStock = true,
                    CreatedAt = new DateTime(2022, 10, 15),
                    UpdatedAt = new DateTime(2026, 8, 20)
                },
                new Book
                {
                    Id = 12,
                    Name = "Midnight in Prague",
                    Title = "Midnight in Prague",
                    Category = "Fiction",
                    Publisher = "Penguin Books",
                    Author = "Thomas Wright",
                    Description = "A detective follows a mysterious trail through the streets of Prague.",
                    PublicationDate = new DateTime(2020, 12, 1),
                    Height = 8.5,
                    Width = 5.5,
                    Price = 17.99m,
                    IsBestSeller = true,
                    Genre = "Crime",
                    IsInStock = false,
                    CreatedAt = new DateTime(2020, 12, 8),
                    UpdatedAt = new DateTime(2026, 9, 3)
                },
                new Book
                {
                    Id = 13,
                    Name = "Building Great APIs",
                    Title = "Building Great APIs",
                    Category = "Technology",
                    Publisher = "Manning",
                    Author = "Kevin Morgan",
                    Description = "Designing scalable REST and distributed APIs for modern applications.",
                    PublicationDate = new DateTime(2024, 4, 17),
                    Height = 9.0,
                    Width = 7.0,
                    Price = 39.99m,
                    IsBestSeller = false,
                    Genre = "Software Engineering",
                    IsInStock = true,
                    CreatedAt = new DateTime(2024, 4, 25),
                    UpdatedAt = new DateTime(2026, 9, 8)
                },
                new Book
                {
                    Id = 14,
                    Name = "The Crimson Crown",
                    Title = "The Crimson Crown",
                    Category = "Fantasy",
                    Publisher = "Tor Books",
                    Author = "Victoria Stone",
                    Description = "A reluctant heir must reclaim a kingdom stolen by an ancient enemy.",
                    PublicationDate = new DateTime(2019, 5, 22),
                    Height = 9.1,
                    Width = 6.0,
                    Price = 23.50m,
                    IsBestSeller = true,
                    Genre = "Fantasy",
                    IsInStock = true,
                    CreatedAt = new DateTime(2019, 5, 30),
                    UpdatedAt = new DateTime(2026, 7, 22)
                },
                new Book
                {
                    Id = 15,
                    Name = "The Psychology of Success",
                    Title = "The Psychology of Success",
                    Category = "Self Development",
                    Publisher = "Random House",
                    Author = "Michael Turner",
                    Description = "Practical strategies for developing productive habits and achieving long-term goals.",
                    PublicationDate = new DateTime(2021, 1, 19),
                    Height = 8.9,
                    Width = 5.9,
                    Price = 24.99m,
                    IsBestSeller = true,
                    Genre = "Personal Development",
                    IsInStock = true,
                    CreatedAt = new DateTime(2021, 1, 25),
                    UpdatedAt = new DateTime(2026, 8, 12)
                },
                new Book
                {
                    Id = 16,
                    Name = "Ancient Roads",
                    Title = "Ancient Roads",
                    Category = "History",
                    Publisher = "Cambridge University Press",
                    Author = "Edward Collins",
                    Description = "A journey through the roads, trade routes and cultures of the ancient world.",
                    PublicationDate = new DateTime(2018, 9, 14),
                    Height = 9.7,
                    Width = 6.8,
                    Price = 36.50m,
                    IsBestSeller = false,
                    Genre = "History",
                    IsInStock = true,
                    CreatedAt = new DateTime(2018, 9, 20),
                    UpdatedAt = new DateTime(2026, 6, 30)
                },
                new Book
                {
                    Id = 17,
                    Name = "The Digital Mind",
                    Title = "The Digital Mind",
                    Category = "Technology",
                    Publisher = "Springer",
                    Author = "Alan Peterson",
                    Description = "An exploration of artificial intelligence and its impact on modern society.",
                    PublicationDate = new DateTime(2023, 6, 6),
                    Height = 9.4,
                    Width = 6.9,
                    Price = 41.75m,
                    IsBestSeller = false,
                    Genre = "Artificial Intelligence",
                    IsInStock = true,
                    CreatedAt = new DateTime(2023, 6, 15),
                    UpdatedAt = new DateTime(2026, 9, 6)
                },
                new Book
                {
                    Id = 18,
                    Name = "Summer at Willow Lake",
                    Title = "Summer at Willow Lake",
                    Category = "Romance",
                    Publisher = "Harlequin",
                    Author = "Emily Parker",
                    Description = "A summer vacation becomes an unexpected second chance at love.",
                    PublicationDate = new DateTime(2020, 6, 3),
                    Height = 8.2,
                    Width = 5.2,
                    Price = 13.99m,
                    IsBestSeller = true,
                    Genre = "Romance",
                    IsInStock = true,
                    CreatedAt = new DateTime(2020, 6, 10),
                    UpdatedAt = new DateTime(2026, 7, 5)
                },
                new Book
                {
                    Id = 19,
                    Name = "The Hidden Signal",
                    Title = "The Hidden Signal",
                    Category = "Thriller",
                    Publisher = "Macmillan",
                    Author = "George Russell",
                    Description = "A communications engineer intercepts a signal that was never meant to be heard.",
                    PublicationDate = new DateTime(2022, 2, 24),
                    Height = 8.8,
                    Width = 5.8,
                    Price = 20.99m,
                    IsBestSeller = true,
                    Genre = "Thriller",
                    IsInStock = false,
                    CreatedAt = new DateTime(2022, 3, 1),
                    UpdatedAt = new DateTime(2026, 9, 4)
                },
                new Book
                {
                    Id = 20,
                    Name = "Database Design Fundamentals",
                    Title = "Database Design Fundamentals",
                    Category = "Technology",
                    Publisher = "Apress",
                    Author = "Brian Evans",
                    Description = "A practical guide to relational database design, normalization and performance.",
                    PublicationDate = new DateTime(2024, 1, 9),
                    Height = 9.1,
                    Width = 7.0,
                    Price = 38.99m,
                    IsBestSeller = false,
                    Genre = "Database",
                    IsInStock = true,
                    CreatedAt = new DateTime(2024, 1, 15),
                    UpdatedAt = new DateTime(2026, 8, 29)
                },

                new Book
                {
                    Id = 21,
                    Name = "The Green Valley",
                    Title = "The Green Valley",
                    Category = "Fiction",
                    Publisher = "Knopf",
                    Author = "Rachel Moore",
                    Description = "A family moves to a remote valley where old rivalries slowly return.",
                    PublicationDate = new DateTime(2019, 2, 13),
                    Height = 8.4,
                    Width = 5.4,
                    Price = 16.99m,
                    IsBestSeller = false,
                    Genre = "Drama",
                    IsInStock = true,
                    CreatedAt = new DateTime(2019, 2, 20),
                    UpdatedAt = new DateTime(2026, 5, 20)
                },
                new Book
                {
                    Id = 22,
                    Name = "Secrets of the Deep",
                    Title = "Secrets of the Deep",
                    Category = "Science",
                    Publisher = "National Geographic",
                    Author = "David Hunter",
                    Description = "Discoveries from the deepest regions of Earth's oceans.",
                    PublicationDate = new DateTime(2022, 8, 16),
                    Height = 10.2,
                    Width = 8.0,
                    Price = 29.99m,
                    IsBestSeller = true,
                    Genre = "Oceanography",
                    IsInStock = true,
                    CreatedAt = new DateTime(2022, 8, 25),
                    UpdatedAt = new DateTime(2026, 8, 16)
                },
                new Book
                {
                    Id = 23,
                    Name = "Mastering Azure",
                    Title = "Mastering Azure",
                    Category = "Technology",
                    Publisher = "Packt Publishing",
                    Author = "Christopher Bell",
                    Description = "Deploying, securing and managing enterprise workloads in Microsoft Azure.",
                    PublicationDate = new DateTime(2024, 5, 7),
                    Height = 9.3,
                    Width = 7.1,
                    Price = 44.99m,
                    IsBestSeller = true,
                    Genre = "Cloud Computing",
                    IsInStock = true,
                    CreatedAt = new DateTime(2024, 5, 15),
                    UpdatedAt = new DateTime(2026, 9, 9)
                },
                new Book
                {
                    Id = 24,
                    Name = "The Clockmaker's Daughter",
                    Title = "The Clockmaker's Daughter",
                    Category = "Historical Fiction",
                    Publisher = "Vintage",
                    Author = "Amelia Foster",
                    Description = "A young woman uncovers a secret hidden inside her father's greatest invention.",
                    PublicationDate = new DateTime(2018, 3, 27),
                    Height = 8.6,
                    Width = 5.6,
                    Price = 18.50m,
                    IsBestSeller = true,
                    Genre = "Historical Fiction",
                    IsInStock = true,
                    CreatedAt = new DateTime(2018, 4, 2),
                    UpdatedAt = new DateTime(2026, 6, 14)
                },
                new Book
                {
                    Id = 25,
                    Name = "Clean Architecture",
                    Title = "Clean Architecture",
                    Category = "Technology",
                    Publisher = "Pearson",
                    Author = "Martin Edwards",
                    Description = "Principles and patterns for building maintainable enterprise software systems.",
                    PublicationDate = new DateTime(2021, 10, 12),
                    Height = 9.0,
                    Width = 7.0,
                    Price = 43.99m,
                    IsBestSeller = true,
                    Genre = "Software Engineering",
                    IsInStock = true,
                    CreatedAt = new DateTime(2021, 10, 20),
                    UpdatedAt = new DateTime(2026, 9, 7)
                },

                new Book
                {
                    Id = 26,
                    Name = "The Mountain Path",
                    Title = "The Mountain Path",
                    Category = "Adventure",
                    Publisher = "Random House",
                    Author = "Daniel Brooks",
                    Description = "Three climbers attempt an unexplored route through a remote mountain range.",
                    PublicationDate = new DateTime(2017, 7, 18),
                    Height = 8.7,
                    Width = 5.7,
                    Price = 17.99m,
                    IsBestSeller = false,
                    Genre = "Adventure",
                    IsInStock = true,
                    CreatedAt = new DateTime(2017, 7, 25),
                    UpdatedAt = new DateTime(2026, 5, 18)
                },
                new Book
                {
                    Id = 27,
                    Name = "Introduction to Quantum Physics",
                    Title = "Introduction to Quantum Physics",
                    Category = "Science",
                    Publisher = "Oxford University Press",
                    Author = "Steven Clarke",
                    Description = "An accessible introduction to the fundamental concepts of quantum physics.",
                    PublicationDate = new DateTime(2020, 9, 29),
                    Height = 9.6,
                    Width = 7.0,
                    Price = 39.50m,
                    IsBestSeller = false,
                    Genre = "Physics",
                    IsInStock = true,
                    CreatedAt = new DateTime(2020, 10, 5),
                    UpdatedAt = new DateTime(2026, 7, 28)
                },
                new Book
                {
                    Id = 28,
                    Name = "The Blue Lantern",
                    Title = "The Blue Lantern",
                    Category = "Mystery",
                    Publisher = "Little, Brown and Company",
                    Author = "Grace Wilson",
                    Description = "A private investigator follows a trail of clues connected to a mysterious blue lantern.",
                    PublicationDate = new DateTime(2021, 4, 20),
                    Height = 8.5,
                    Width = 5.5,
                    Price = 18.99m,
                    IsBestSeller = false,
                    Genre = "Mystery",
                    IsInStock = false,
                    CreatedAt = new DateTime(2021, 4, 28),
                    UpdatedAt = new DateTime(2026, 8, 24)
                },
                new Book
                {
                    Id = 29,
                    Name = "Practical Docker",
                    Title = "Practical Docker",
                    Category = "Technology",
                    Publisher = "Manning",
                    Author = "Andrew Cooper",
                    Description = "Containerizing applications and building reliable development environments with Docker.",
                    PublicationDate = new DateTime(2023, 11, 14),
                    Height = 9.2,
                    Width = 7.1,
                    Price = 36.99m,
                    IsBestSeller = false,
                    Genre = "DevOps",
                    IsInStock = true,
                    CreatedAt = new DateTime(2023, 11, 20),
                    UpdatedAt = new DateTime(2026, 9, 11)
                },
                new Book
                {
                    Id = 30,
                    Name = "Letters from Lisbon",
                    Title = "Letters from Lisbon",
                    Category = "Romance",
                    Publisher = "Penguin Books",
                    Author = "Anna Richardson",
                    Description = "A collection of letters reveals a love story separated by continents and decades.",
                    PublicationDate = new DateTime(2019, 10, 7),
                    Height = 8.3,
                    Width = 5.3,
                    Price = 15.99m,
                    IsBestSeller = true,
                    Genre = "Romance",
                    IsInStock = true,
                    CreatedAt = new DateTime(2019, 10, 15),
                    UpdatedAt = new DateTime(2026, 6, 25)
                },

                new Book
                {
                    Id = 31,
                    Name = "The AI Revolution",
                    Title = "The AI Revolution",
                    Category = "Technology",
                    Publisher = "Wiley",
                    Author = "Jonathan Miller",
                    Description = "How artificial intelligence is transforming software, business and everyday life.",
                    PublicationDate = new DateTime(2024, 6, 11),
                    Height = 9.4,
                    Width = 7.0,
                    Price = 31.99m,
                    IsBestSeller = true,
                    Genre = "Artificial Intelligence",
                    IsInStock = true,
                    CreatedAt = new DateTime(2024, 6, 20),
                    UpdatedAt = new DateTime(2026, 9, 12)
                },
                new Book
                {
                    Id = 32,
                    Name = "The Winter Garden",
                    Title = "The Winter Garden",
                    Category = "Fiction",
                    Publisher = "Scribner",
                    Author = "Olivia Carter",
                    Description = "Two sisters return home after their mother's death and uncover a family secret.",
                    PublicationDate = new DateTime(2018, 11, 6),
                    Height = 8.6,
                    Width = 5.6,
                    Price = 17.50m,
                    IsBestSeller = true,
                    Genre = "Drama",
                    IsInStock = true,
                    CreatedAt = new DateTime(2018, 11, 15),
                    UpdatedAt = new DateTime(2026, 7, 2)
                },
                new Book
                {
                    Id = 33,
                    Name = "Cyber Threat Intelligence",
                    Title = "Cyber Threat Intelligence",
                    Category = "Technology",
                    Publisher = "Apress",
                    Author = "Matthew Green",
                    Description = "Techniques for collecting, analyzing and operationalizing cyber threat intelligence.",
                    PublicationDate = new DateTime(2023, 3, 21),
                    Height = 9.3,
                    Width = 7.0,
                    Price = 46.99m,
                    IsBestSeller = false,
                    Genre = "Cybersecurity",
                    IsInStock = true,
                    CreatedAt = new DateTime(2023, 3, 28),
                    UpdatedAt = new DateTime(2026, 8, 31)
                },
                new Book
                {
                    Id = 34,
                    Name = "The Desert Kingdom",
                    Title = "The Desert Kingdom",
                    Category = "Fantasy",
                    Publisher = "Orbit",
                    Author = "Samuel King",
                    Description = "An exiled prince crosses a dangerous desert to reclaim his family's throne.",
                    PublicationDate = new DateTime(2020, 2, 18),
                    Height = 8.9,
                    Width = 5.9,
                    Price = 20.99m,
                    IsBestSeller = true,
                    Genre = "Fantasy",
                    IsInStock = true,
                    CreatedAt = new DateTime(2020, 2, 25),
                    UpdatedAt = new DateTime(2026, 6, 19)
                },
                new Book
                {
                    Id = 35,
                    Name = "A Brief History of Flight",
                    Title = "A Brief History of Flight",
                    Category = "History",
                    Publisher = "Smithsonian Books",
                    Author = "Richard Adams",
                    Description = "The development of aviation from the earliest experiments to modern aircraft.",
                    PublicationDate = new DateTime(2016, 8, 9),
                    Height = 10.0,
                    Width = 7.5,
                    Price = 28.99m,
                    IsBestSeller = false,
                    Genre = "History",
                    IsInStock = false,
                    CreatedAt = new DateTime(2016, 8, 20),
                    UpdatedAt = new DateTime(2026, 5, 10)
                },
                new Book
                {
                    Id = 36,
                    Name = "Effective SQL",
                    Title = "Effective SQL",
                    Category = "Technology",
                    Publisher = "Addison-Wesley",
                    Author = "Peter Morgan",
                    Description = "Practical techniques for writing efficient and scalable SQL queries.",
                    PublicationDate = new DateTime(2022, 6, 28),
                    Height = 9.1,
                    Width = 7.0,
                    Price = 40.99m,
                    IsBestSeller = false,
                    Genre = "Database",
                    IsInStock = true,
                    CreatedAt = new DateTime(2022, 7, 5),
                    UpdatedAt = new DateTime(2026, 9, 1)
                },
                new Book
                {
                    Id = 37,
                    Name = "The Red Door",
                    Title = "The Red Door",
                    Category = "Thriller",
                    Publisher = "Macmillan",
                    Author = "Jennifer Adams",
                    Description = "A journalist discovers that every victim in a mysterious case visited the same house.",
                    PublicationDate = new DateTime(2021, 9, 13),
                    Height = 8.5,
                    Width = 5.5,
                    Price = 19.99m,
                    IsBestSeller = true,
                    Genre = "Thriller",
                    IsInStock = true,
                    CreatedAt = new DateTime(2021, 9, 20),
                    UpdatedAt = new DateTime(2026, 8, 15)
                },
                new Book
                {
                    Id = 38,
                    Name = "Understanding Networks",
                    Title = "Understanding Networks",
                    Category = "Technology",
                    Publisher = "Cisco Press",
                    Author = "Mark Henderson",
                    Description = "A practical introduction to networking protocols, architecture and troubleshooting.",
                    PublicationDate = new DateTime(2023, 7, 18),
                    Height = 9.4,
                    Width = 7.1,
                    Price = 37.99m,
                    IsBestSeller = false,
                    Genre = "Networking",
                    IsInStock = true,
                    CreatedAt = new DateTime(2023, 7, 25),
                    UpdatedAt = new DateTime(2026, 8, 27)
                },
                new Book
                {
                    Id = 39,
                    Name = "The Lost Expedition",
                    Title = "The Lost Expedition",
                    Category = "Adventure",
                    Publisher = "National Geographic",
                    Author = "William Parker",
                    Description = "A modern expedition searches for explorers who disappeared nearly a century ago.",
                    PublicationDate = new DateTime(2019, 6, 12),
                    Height = 9.0,
                    Width = 6.0,
                    Price = 22.99m,
                    IsBestSeller = true,
                    Genre = "Adventure",
                    IsInStock = true,
                    CreatedAt = new DateTime(2019, 6, 20),
                    UpdatedAt = new DateTime(2026, 7, 10)
                },
                new Book
                {
                    Id = 40,
                    Name = "The Future of Work",
                    Title = "The Future of Work",
                    Category = "Business",
                    Publisher = "McGraw-Hill",
                    Author = "Daniel Peterson",
                    Description = "How automation, remote work and artificial intelligence are reshaping careers.",
                    PublicationDate = new DateTime(2022, 11, 1),
                    Height = 9.0,
                    Width = 6.5,
                    Price = 27.99m,
                    IsBestSeller = true,
                    Genre = "Business",
                    IsInStock = true,
                    CreatedAt = new DateTime(2022, 11, 10),
                    UpdatedAt = new DateTime(2026, 9, 5)
                },

                new Book
                {
                    Id = 41,
                    Name = "The House on the Hill",
                    Title = "The House on the Hill",
                    Category = "Horror",
                    Publisher = "Penguin Books",
                    Author = "Rebecca Stone",
                    Description = "A family inherits an abandoned house where strange events begin after sunset.",
                    PublicationDate = new DateTime(2017, 10, 31),
                    Height = 8.4,
                    Width = 5.4,
                    Price = 16.99m,
                    IsBestSeller = true,
                    Genre = "Horror",
                    IsInStock = true,
                    CreatedAt = new DateTime(2017, 11, 5),
                    UpdatedAt = new DateTime(2026, 7, 30)
                },
                new Book
                {
                    Id = 42,
                    Name = "Designing Distributed Systems",
                    Title = "Designing Distributed Systems",
                    Category = "Technology",
                    Publisher = "O'Reilly Media",
                    Author = "Brandon Lewis",
                    Description = "Architectural patterns for reliable distributed and cloud-native applications.",
                    PublicationDate = new DateTime(2024, 3, 19),
                    Height = 9.5,
                    Width = 7.2,
                    Price = 48.99m,
                    IsBestSeller = false,
                    Genre = "Distributed Systems",
                    IsInStock = true,
                    CreatedAt = new DateTime(2024, 3, 25),
                    UpdatedAt = new DateTime(2026, 9, 13)
                },
                new Book
                {
                    Id = 43,
                    Name = "The Emerald Sea",
                    Title = "The Emerald Sea",
                    Category = "Fantasy",
                    Publisher = "HarperCollins",
                    Author = "Lillian Woods",
                    Description = "A sailor discovers an enchanted sea where ancient creatures still survive.",
                    PublicationDate = new DateTime(2020, 5, 26),
                    Height = 8.8,
                    Width = 5.8,
                    Price = 19.99m,
                    IsBestSeller = false,
                    Genre = "Fantasy",
                    IsInStock = true,
                    CreatedAt = new DateTime(2020, 6, 2),
                    UpdatedAt = new DateTime(2026, 7, 17)
                },
                new Book
                {
                    Id = 44,
                    Name = "The Science of Sleep",
                    Title = "The Science of Sleep",
                    Category = "Science",
                    Publisher = "Wiley",
                    Author = "Dr. Helen Morris",
                    Description = "An accessible exploration of sleep, dreams and the science behind healthy rest.",
                    PublicationDate = new DateTime(2021, 12, 7),
                    Height = 9.2,
                    Width = 6.5,
                    Price = 25.99m,
                    IsBestSeller = true,
                    Genre = "Neuroscience",
                    IsInStock = true,
                    CreatedAt = new DateTime(2021, 12, 15),
                    UpdatedAt = new DateTime(2026, 8, 5)
                },
                new Book
                {
                    Id = 45,
                    Name = "Git for Developers",
                    Title = "Git for Developers",
                    Category = "Technology",
                    Publisher = "Apress",
                    Author = "Eric Johnson",
                    Description = "Mastering Git workflows, branching strategies and collaborative development.",
                    PublicationDate = new DateTime(2023, 4, 4),
                    Height = 8.9,
                    Width = 6.8,
                    Price = 29.99m,
                    IsBestSeller = false,
                    Genre = "Programming",
                    IsInStock = true,
                    CreatedAt = new DateTime(2023, 4, 10),
                    UpdatedAt = new DateTime(2026, 8, 22)
                },
                new Book
                {
                    Id = 46,
                    Name = "The Long Road Home",
                    Title = "The Long Road Home",
                    Category = "Fiction",
                    Publisher = "Scribner",
                    Author = "Margaret Ellis",
                    Description = "After years abroad, a woman returns home and confronts the choices she left behind.",
                    PublicationDate = new DateTime(2018, 1, 16),
                    Height = 8.5,
                    Width = 5.5,
                    Price = 15.99m,
                    IsBestSeller = true,
                    Genre = "Drama",
                    IsInStock = false,
                    CreatedAt = new DateTime(2018, 1, 25),
                    UpdatedAt = new DateTime(2026, 6, 8)
                },
                new Book
                {
                    Id = 47,
                    Name = "Secure Software Development",
                    Title = "Secure Software Development",
                    Category = "Technology",
                    Publisher = "Packt Publishing",
                    Author = "Steven Walker",
                    Description = "Integrating security practices into modern software development lifecycles.",
                    PublicationDate = new DateTime(2024, 7, 2),
                    Height = 9.3,
                    Width = 7.0,
                    Price = 43.50m,
                    IsBestSeller = false,
                    Genre = "Cybersecurity",
                    IsInStock = true,
                    CreatedAt = new DateTime(2024, 7, 10),
                    UpdatedAt = new DateTime(2026, 9, 14)
                },
                new Book
                {
                    Id = 48,
                    Name = "The Golden Compass",
                    Title = "The Golden Compass",
                    Category = "Adventure",
                    Publisher = "Vintage",
                    Author = "Charles Bennett",
                    Description = "An explorer follows an ancient map toward a legendary city hidden beyond the mountains.",
                    PublicationDate = new DateTime(2016, 5, 24),
                    Height = 8.7,
                    Width = 5.7,
                    Price = 17.50m,
                    IsBestSeller = false,
                    Genre = "Adventure",
                    IsInStock = true,
                    CreatedAt = new DateTime(2016, 6, 1),
                    UpdatedAt = new DateTime(2026, 5, 28)
                },
                new Book
                {
                    Id = 49,
                    Name = "Leadership in Practice",
                    Title = "Leadership in Practice",
                    Category = "Business",
                    Publisher = "Harvard Business Review Press",
                    Author = "Richard Thompson",
                    Description = "Lessons and strategies for leading teams through change and uncertainty.",
                    PublicationDate = new DateTime(2022, 3, 8),
                    Height = 9.0,
                    Width = 6.4,
                    Price = 26.99m,
                    IsBestSeller = true,
                    Genre = "Leadership",
                    IsInStock = true,
                    CreatedAt = new DateTime(2022, 3, 15),
                    UpdatedAt = new DateTime(2026, 8, 10)
                },
                new Book
                {
                    Id = 50,
                    Name = "The Infinite Library",
                    Title = "The Infinite Library",
                    Category = "Fantasy",
                    Publisher = "Bloomsbury",
                    Author = "Alexander Gray",
                    Description = "A librarian discovers a hidden wing containing books that describe events before they happen.",
                    PublicationDate = new DateTime(2023, 8, 22),
                    Height = 8.9,
                    Width = 5.9,
                    Price = 21.99m,
                    IsBestSeller = true,
                    Genre = "Fantasy",
                    IsInStock = true,
                    CreatedAt = new DateTime(2023, 8, 30),
                    UpdatedAt = new DateTime(2026, 9, 15)
                }
            };
            return books2;
            */
            return Enumerable.Empty<Book>();
        }
    }
}
